# Default values for drone-runner-docker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Mapping between IP and hostnames that will be injected as entries in the pod's hosts files
# https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
hostAliases: []
# - ip: 10.20.30.40
#   hostnames:
#   - gitea-127.0.0.1.sslip.io
replicaCount: 2

## The official drone docker runner image, change tag to use a different version.
## ref: https://hub.docker.com/r/drone/drone-runner-docker/tags/
##
image:
  registry: docker.io
  repository: drone/drone-runner-docker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.8.1

## If you'd like to make additional files or volumes available to the runner, declare additional
## Volumes here per the Pod spec's "volumes" section of the dind container
## Ref: https://kubernetes.io/docs/concepts/storage/volumes/
##
extraVolumes:
  - name: storage
    emptyDir: {}
## If you have declared extra volumes, mount them here, per the Pod Container's
## "volumeMounts" section.
##
extraVolumeMounts: []

## Values used only for dind container
dind:
  ## The official docker (dind) image, change tag to use a different version.
  ## ref: https://hub.docker.com/r/library/docker/tags/
  ##
  registry: docker.io
  repository: docker
  tag: 20-dind
  pullPolicy: IfNotPresent
  command:
    - "dockerd"
  commandArgs:
    - "--host"
    - "tcp://localhost:2375"
  securityContext:
    privileged: true
  ## If you have declared extra volumes, mount them here, per the Pod Container's
  ## "volumeMounts" section of dind container
  ##
  extraVolumeMounts:
    - name: storage
      mountPath: /var/lib/docker
      subPath: docker

## Values used only for the Drone Garbage Collector container
gc:
  enabled: false
  ## The official Drone Garbage collector image, change tag to use a different version.
  ## ref: https://hub.docker.com/r/drone/gc/tags
  ##
  registry: docker.io
  repository: drone/gc
  tag: 1.0.0
  pullPolicy: IfNotPresent
  securityContext: {}
  env:
    GC_DEBUG: false
    GC_DEBUG_COLOR: "false"
    GC_DEBUG_PRETTY: "false"
    GC_IGNORE_IMAGES: ""
    GC_IGNORE_CONTAINERS: ""
    GC_INTERVAL: "5m"
    GC_CACHE: "5gb"
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

imagePullSecrets: []

## When the runner receives a SIGTERM/SIGINT (config update, upgrade, etc), it will wait until
## all jobs that particular pod has spawned complete. It is for this reason that you'll want
## to make sure that this value is longer than your longest job.
terminationGracePeriodSeconds: 3600

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: drone-runner-sa

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
  requests:
    cpu: 100m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
  stabilizationWindowSeconds: 600
  periodSeconds: 60

nodeSelector: {}

tolerations: []

affinity: {}

## If you'd like to provide your own Kubernetes Secret object instead of passing your values
## in un-encrypted, pass in the name of a created + populated Secret in the same Namespace
## as the Docker runner. All secrets within this configmap will be mounted as environment
## variables, with each key/value mapping to a corresponding environment variable on the
## Docker runner.
##
extraSecretNamesForEnvFrom:
  - drone-runner-secrets

## The keys within the "env" map are mounted as environment variables on the Kubernetes runner pod.
## See the full reference of Kubernetes runner environment variables here:
## Ref: https://docs.drone.io/runner/docker/configuration/reference/
##
env:
  ## The docker host to be used by the drone-runner-docker when connecting
  ## to the docker daemon, defaults to the dind(sidecar) docker daemon
  DOCKER_HOST: "tcp://localhost:2375"
  ## REQUIRED: Set the secret secret token that the Docker runner will use
  ## to authenticate. This is commented out in order to leave you the ability to set the
  ## key via a separately provisioned secret (see extraSecretNamesForEnvFrom above).
  ## Ref: https://docs.drone.io/runner/docker/configuration/reference/drone-rpc-secret/
  ##
  # DRONE_RPC_SECRET:

  ## Mount native identity to all steps
  ## This is no more or less secure then allowing them to be mounted manually which is required
  ## anyways (unless we want to use access keys.)
  DRONE_RUNNER_VOLUMES: /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token

  ## Our defaults
  DRONE_SERVICE_ACCOUNT_DEFAULT: drone-sa

  DRONE_TRACE: true

  DRONE_DEBUG: true

  DRONE_RPC_DUMP_HTTP: false

## class
class:
  # used for toleration and affinity and should map to node labels
  # provided by karpenter
  type: spot
  # used for naming and node tags, etc
  name: spot-test
  cpu: 2100m
  memory: 2.5gi

runner:
  capacity: 1
  privilegedImages: "076263846157.dkr.ecr.us-east-1.amazonaws.com/drone-plugin/ecr, 710267309417.dkr.ecr.us-east-1.amazonaws.com/builder/dnd"

environment: staging

rpc:
  host: drone
  proto: http

plugins:
  secret:
    endpoint: http://drone-plugins:3001
  registry:
    endpoint: http://drone-plugins:3002

kedaScaling:
  enabled: true
  minReplicas: 0
  maxReplicas: 4
  fallbackReplicas: 4
  cooldownPeriod: 600
  scaleDown:
    stabilizationWindowSeconds: 200

resources:
  requests:
    cpu: "500m"
    memory: "250Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
