#fullnameOverride: "supercalafra"

#service:
#  type: LoadBalancer
#  loadBalancerIP: "34.148.171.160"
#  port: 80

#extraSecretNamesForEnvFrom:
#  - drone-rpc-secret
#  - drone-github-client-secret

extraVolumes:
  - name: storage
    emptyDir: {}

dind:
  ## The official docker (dind) image, change tag to use a different version.
  ## ref: https://hub.docker.com/r/library/docker/tags/
  ##
  repository: docker
  tag: 20-dind
  pullPolicy: IfNotPresent
  command:
    - "dockerd"
  commandArgs:
    - "--host"
    - "tcp://localhost:2375"
  securityContext:
    privileged: true
  extraVolumeMounts:
    - name: storage
      mountPath: /var/lib/docker
      subPath: docker

## The keys within the "env" map are mounted as environment variables on the Drone server pod.
## See the full reference of Drone server environment variables here:
## Ref: https://docs.drone.io/installation/reference/
##
env:
  ## REQUIRED: Set the user-visible Drone hostname, sans protocol.
  ## Ref: https://docs.drone.io/installation/reference/drone-server-host/
  ##
  DRONE_SERVER_HOST: 458c-146-168-58-81.ngrok.io
  ## The protocol to pair with the value in DRONE_SERVER_HOST (http or https).
  ## Ref: https://docs.drone.io/installation/reference/drone-server-proto/
  ##
  DRONE_SERVER_PROTO: https

  DRONE_SERVER_PORT: ":80"

  #DRONE_RUNNER_PLATFORM: linux/arm64

  DRONE_AGENTS_DISABLED: true

  DOCKER_HOST: "tcp://localhost:2375"

  ## REQUIRED: Set the secret secret token that the Drone server and its Runners will use
  ## to authenticate. This is commented out in order to leave you the ability to set the
  ## key via a separately provisioned secret (see existingSecretName above).
  ## Ref: https://docs.drone.io/installation/reference/drone-rpc-secret/
  ##
  #DRONE_RPC_SECRET: 1d349598ab5dd8326f06874803bed0fe

  DRONE_LOGS_DEBUG: true
  DRONE_GITHUB_CLIENT_ID: 2ad15d79506862775f2c
  DRONE_GITHUB_CLIENT_SECRET: 12d349b41f47403c39b9e60a6409a702d417a89c
